"""Parses a single House Periodic Transaction Report (PTR) PDF into a list
of trade dicts.

The PDF has no real table structure PDF-side (pdfplumber's extract_table()
misaligns columns), and any of the Asset/Amount columns can wrap across
multiple visual lines depending on filer/owner text length. So this buckets
words by column using fixed x-position thresholds (consistent across
filings — these are all generated by the same House Clerk template), then
merges all lines belonging to one transaction block (from the row that
starts a new transaction until the next "Filing Status:" detail row) by
concatenating each column's text across those lines.
"""
import re
import pdfplumber

TYPE_MAP = {
    'P': 'Purchase',
    'S (partial)': 'Sale (Partial)',
    'S (full)': 'Sale (Full)',
    'S': 'Sale',
    'E': 'Exchange',
}
TYPE_RE = re.compile(r'^(P|S \(partial\)|S \(full\)|S|E)$')
# Long asset descriptions sometimes spill a word or two past the Asset
# column's x-boundary into the Type column (e.g. "Class A" -> "A" lands in
# the type bucket, producing "A P"). Match the type token anchored at the
# END of the cell instead, and reclaim anything before it as asset text.
TYPE_TAIL_RE = re.compile(r'(P|S \(partial\)|S \(full\)|S|E)$')
DATE_RE = re.compile(r'^\d{2}/\d{2}/\d{4}$')

TICKER_RE = re.compile(r'\(([A-Z]{1,6}(?:\.[A-Z]{1,3})?)\)\s*\[(ST|OT|CT|GS|MF|OP)\]')
ASSET_TYPE_RE = re.compile(r'\[(ST|OT|CT|GS|MF|OP)\]')
AMOUNT_RE = re.compile(r'\$[\d,]+(?:\s*-\s*\$[\d,]+)?|\$1,000 or less')

# Column x0 boundaries, taken from the header row ("ID Owner Asset
# Transaction Date Notification Amount Cap."), which sits at the same
# position on every filing since they all come from the same generator.
COLUMNS = [
    ('id', 0),
    ('owner', 45),
    ('asset', 85),
    ('type', 245),
    ('date', 305),
    ('notif_date', 360),
    ('amount', 425),
    ('cap_gains', 505),
]

DETAIL_PREFIX_RE = re.compile(r'^[A-Z]\W*[A-Z]?\W*:')


def bucket(x0):
    col = COLUMNS[0][0]
    for name, threshold in COLUMNS:
        if x0 >= threshold:
            col = name
        else:
            break
    return col


def group_lines(words, tol=2.5):
    lines = []
    for w in sorted(words, key=lambda w: (w['top'], w['x0'])):
        for line in lines:
            if abs(line[0]['top'] - w['top']) <= tol:
                line.append(w)
                break
        else:
            lines.append([w])
    return lines


def line_to_columns(line):
    cols = {name: [] for name, _ in COLUMNS}
    for w in sorted(line, key=lambda w: w['x0']):
        cols[bucket(w['x0'])].append(w['text'])
    return {name: ' '.join(texts) for name, texts in cols.items()}


def parse_ptr_pdf(path_or_file):
    trades = []
    member = None
    office = None
    row_dicts = []

    with pdfplumber.open(path_or_file) as pdf:
        for page in pdf.pages:
            words = page.extract_words()
            for line in group_lines(words):
                text = ' '.join(w['text'] for w in sorted(line, key=lambda w: w['x0']))
                m = re.match(r'^Name:\s*(.+)$', text)
                if m:
                    member = m.group(1).strip()
                m = re.match(r'^State/District:\s*(.+)$', text)
                if m:
                    office = m.group(1).strip()
                row_dicts.append(line_to_columns(line))

    def match_type(row):
        m = TYPE_TAIL_RE.search(row['type'].strip())
        if m and DATE_RE.match(row['date'].strip()):
            return m
        return None

    i = 0
    while i < len(row_dicts):
        row = row_dicts[i]
        type_m = match_type(row)
        if type_m:
            overflow = row['type'].strip()[:type_m.start()].strip()
            asset_text = (row['asset'] + ' ' + overflow).strip() if overflow else row['asset']
            amount_text = row['amount']
            txn_type = type_m.group(1)
            date1 = row['date'].strip()
            date2 = row['notif_date'].strip()

            # Pull in continuation lines (wrapped asset/ticker/amount text)
            # until the next "Filing Status:"-style detail row.
            j = i + 1
            while j < len(row_dicts):
                nxt = row_dicts[j]
                full_line = ' '.join(v for v in nxt.values() if v).strip()
                if DETAIL_PREFIX_RE.match(full_line):
                    break
                if match_type(nxt):
                    break  # next transaction started without hitting a detail row
                asset_text += ' ' + nxt['asset']
                amount_text += ' ' + nxt['amount']
                j += 1

            ticker_m = TICKER_RE.search(asset_text)
            asset_type_m = ASSET_TYPE_RE.search(asset_text)
            amount_m = AMOUNT_RE.search(amount_text)
            clean_desc = TICKER_RE.sub('', asset_text)
            clean_desc = ASSET_TYPE_RE.sub('', clean_desc).strip(' -')
            clean_desc = re.sub(r'\s+', ' ', clean_desc)

            if ticker_m:
                trades.append({
                    'member': member,
                    'office': office,
                    'ticker': ticker_m.group(1),
                    'asset_description': clean_desc,
                    'asset_type': asset_type_m.group(1) if asset_type_m else '',
                    'type': TYPE_MAP.get(txn_type, txn_type),
                    'transaction_date': date1,
                    'notification_date': date2,
                    'amount': amount_m.group(0) if amount_m else amount_text.strip(),
                })
            i = j
        else:
            i += 1

    return trades


if __name__ == '__main__':
    import sys, json
    trades = parse_ptr_pdf(sys.argv[1])
    print(json.dumps(trades, indent=2))
    print(f'\n{len(trades)} trades parsed', file=sys.stderr)
